sudo: required

language: python
python:
  - "3.9"

before_script:
  - cd backend
  - pip3 install -r requirements.txt
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - python3 manage.py test

