sudo: required

language: python
python:
  - "3.8"

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.4


before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - pip3 install -r requirements.txt

script:
  - docker-compose run web sh -c "python3 manage.py test orders/tests/test_auth_backends.py orders/tests/test_validators.py && flake8 ."

after_script:
  - docker images
  