sudo: required

language: python
python:
  - "3.8"

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.4

install:
  - pip install -r requirements.txt

script:
  - docker-compose run web sh -c "python manage.py test && flake8 ."

after_script:
  - docker images
  