version: '3.4'

services:
  db:
    image: postgres:latest
    container_name: db
    environment: 
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
    volumes:
      - $PWD/pg-data/:/var/lib/postgresql/data

  web:
    build: .
    container_name: web
    entrypoint: /code/bin/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - db