version: '3.4'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    container_name: web
    entrypoint: /code/bin/build.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - db

volumes:
  postgres_data:
