version: '3.4'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres

  migration:
    build: .
    command: python3 manage.py migrate
    volumes:
      - .:/usr/src/app
    depends_on: 
      - db


  web:
    build: .
    container_name: webserver
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on: 
      - db
      - migration