version: '3.4'

services:
  db:
    image: postgres
    container_name: db
    environment: 
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres

      
  migration:
    build: .
    container_name: migration
    command: python3 manage.py migrate
    volumes:
      - .:/code
    depends_on: 
      - db


  web:
    build: .
    container_name: web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - migration