# Generated by Django 3.1.7 on 2021-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210411_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=5),
            preserve_default=False,
        ),
    ]
