# Generated by Django 3.0.6 on 2020-07-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200610_0348'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='orders_category',
        ),
    ]
