# Generated by Django 3.1.7 on 2021-04-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200714_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='toppings',
        ),
        migrations.AlterField(
            model_name='extra',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='extras', to='orders.Extra'),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
